//
//  SumsubVerification.swift
//  Minimal Sumsub Mobile SDK integration for iOS.
//
//  Generated by the sumsub-integrate-msdk skill. Adapt the token fetch to your
//  backend. The App Token / secret must NEVER ship in the app — only the
//  short-lived access token returned by your server is used here.
//
//  Same launch path for UIKit and SwiftUI: the SDK presents itself.
//

import UIKit
import IdensicMobileSDK

// Swift 6 strict concurrency: mark this class `@MainActor` — see
// references/swift6-concurrency.md.
final class SumsubVerification {

    /// Launch the flow. Presents from `presenter`, or from the key window's root
    /// VC when `presenter` is nil (the usual case for SwiftUI — pass nil).
    /// `onDismiss` fires when the user closes the flow.
    func start(from presenter: UIViewController? = nil, onDismiss: (() -> Void)? = nil) {
        makeSDK(onDismiss: onDismiss) { sdk in
            if let presenter {
                sdk.present(from: presenter)
            } else {
                sdk.present()   // present from the key window's root VC
            }
        }
    }

    /// Shared async orchestration: fetch the token, then build the SDK on the main
    /// thread and present it. Don't retain `sdk` — once presented, `mainVC` keeps the
    /// SDK alive for the whole flow and both are released together on dismiss.
    private func makeSDK(onDismiss: (() -> Void)?,
                         _ ready: @escaping (SNSMobileSDK) -> Void) {
        fetchAccessToken { [weak self] token in
            guard let self, let token else {
                print("Sumsub: no access token from backend")
                return
            }

            DispatchQueue.main.async {
                guard let sdk = self.configuredSDK(
                    token: token,
                    onDismiss: onDismiss
                ) else {
                    return
                }

                ready(sdk)
            }
        }
    }

    /// Builds a ready, fully-wired SDK. Call on the **main thread** — init touches UIKit.
    /// Returns `nil` if init failed (`verboseStatus` says why). `[weak self]` keeps the
    /// token-refresh handler from retaining this launch object.
    private func configuredSDK(token: String, onDismiss: (() -> Void)?) -> SNSMobileSDK? {
        let sdk = SNSMobileSDK(accessToken: token)

        // A failed init still returns an object — verboseStatus says why.
        guard sdk.isReady else {
            print("Sumsub init failed: \(sdk.verboseStatus)")
            return nil
        }

        // REQUIRED: refresh the token when it expires, or the flow stalls.
        sdk.tokenExpirationHandler { [weak self] onComplete in
            self?.fetchAccessToken { newToken in
                onComplete(newToken)   // pass nil to fail the session
            }
        }

        // Optional progress tracking.
        sdk.onStatusDidChange { sdk, prevStatus in
            print("Sumsub status: \(sdk.description(for: prevStatus)) "
                + "→ \(sdk.description(for: sdk.status))")
        }

        sdk.onDidDismiss { _ in
            // Authoritative verdict comes from your backend (webhook + applicant GET).
            onDismiss?()
        }

        // If you style the SDK, set the theme here, before handing it back:
        // sdk.theme = SumsubTheme()   // see sumsub-theme-msdk

        return sdk
    }

    /// Replace with a real call to YOUR backend, which signs
    /// POST /resources/accessTokens with the Sumsub App Token.
    private func fetchAccessToken(completion: @escaping (String?) -> Void) {
        // URLSession.shared.dataTask(...) { ... completion(token) }.resume()
        completion(nil)
    }
}
