//
//  SumsubIntegration.kt
//  Sumsub Mobile SDK glue for Android — coroutine-first, architecture-agnostic.
//
//  Generated by the sumsub-integrate-msdk skill. This file holds ONLY the reusable
//  Sumsub glue; it does not own threading, lifecycle, or UI. You drive it from your
//  own ViewModel / coroutine scope (see the launch stage for MVVM, MVI & Compose
//  wiring). The App Token / secret must NEVER ship in the app — only the short-lived
//  access token your backend signs is used here.
//
//  Import paths match the current SDK package layout (com.sumsub.sns.core.*) —
//  let the IDE confirm/adjust them if your version differs.
//

package com.example.app.sumsub

import android.app.Activity
import android.util.Log
import com.sumsub.sns.core.SNSMobileSDK
import com.sumsub.sns.core.data.listener.TokenExpirationHandler
import com.sumsub.sns.core.data.model.SNSCompletionResult
import com.sumsub.sns.core.data.model.SNSException
import com.sumsub.sns.core.data.model.SNSSDKState
import kotlinx.coroutines.runBlocking
import java.util.Locale

/**
 * The seam into your app's architecture. Implement it in your data/domain layer — a
 * repository, a use-case, a Retrofit/Ktor service wrapper, whatever your app
 * already uses for I/O — to return a fresh Sumsub access token signed by your backend
 * (`POST /resources/accessTokens`, App Token-signed server-side).
 *
 * It is a `suspend` function: do the network call with your normal stack and dispatcher
 * (e.g. `withContext(Dispatchers.IO) { api.accessToken() }`). The launcher below calls it
 * both for the initial launch (from your ViewModel's scope) and for mid-session refresh.
 */
fun interface SumsubTokenProvider {
    suspend fun fetchAccessToken(): String
}

/**
 * Sumsub SDK launcher. Construct it with your [SumsubTokenProvider] (inject the
 * same repository instance your ViewModel uses), then call [present] once you already
 * hold a token — typically from your ViewModel-driven event, on the main thread.
 */
class SumsubLauncher(private val tokenProvider: SumsubTokenProvider) {

    /**
     * Build and launch the SDK. Call on the MAIN thread with the hosting [activity] and a
     * token you already fetched (your ViewModel fetched it in `viewModelScope`).
     */
    fun present(activity: Activity, accessToken: String) {
        val sdk = SNSMobileSDK.Builder(activity)
            .withAccessToken(accessToken, onTokenExpiration = tokenExpirationHandler)
            .withHandlers(
                // Optional progress tracking — surface it to your state holder if useful.
                onStateChanged = { newState: SNSSDKState, prevState: SNSSDKState ->
                    Log.d("Sumsub", "State: $prevState -> $newState")
                },
                // Fires when the flow closes. UX only — NOT the source of truth. The
                // authoritative verdict comes from your backend (webhook + applicant GET).
                onCompleted = { result: SNSCompletionResult, _: SNSSDKState ->
                    when (result) {
                        is SNSCompletionResult.SuccessTermination ->
                            Log.d("Sumsub", "Flow finished")
                        is SNSCompletionResult.AbnormalTermination ->
                            Log.e("Sumsub", "Flow closed with error", result.exception)
                    }
                },
                onError = { e: SNSException -> Log.e("Sumsub", "SDK error", e) },
            )
            // Device locale by default; pass a fixed Locale("en") etc. to force a language.
            .withLocale(Locale.getDefault())
            // If you style the SDK, attach the theme here — see sumsub-theme-msdk skill:
            // .withTheme(sumsubTheme(activity))
            .build()

        sdk.launch()
    }

    /**
     * REQUIRED token refresh. The SDK calls `onTokenExpired()` SYNCHRONOUSLY on a
     * background thread and blocks on the return value, so we bridge the suspend provider
     * with `runBlocking` — this is the one place it is correct: we are already off the
     * main thread and MUST return a value. Returning null aborts the session.
     */
    private val tokenExpirationHandler = object : TokenExpirationHandler {
        override fun onTokenExpired(): String? = runBlocking {
            runCatching { tokenProvider.fetchAccessToken() }
                .onFailure { Log.e("Sumsub", "Token refresh failed", it) }
                .getOrNull()
        }
    }
}
