//
//  SumsubSwiftUI.swift
//  Optional SwiftUI launch helper for the Sumsub Mobile SDK.
//
//  Generated by the sumsub-integrate-msdk skill. A thin ObservableObject that forwards
//  to SumsubVerification.start() — the SDK presents itself. Optional: a view can hold
//  SumsubVerification directly instead.
//
//  Usage:
//      struct MyView: View {
//          @StateObject private var sumsub = SumsubPresenter()   // survives the async token fetch
//          var body: some View {
//              Button("Verify") { sumsub.launch() }
//          }
//      }
//

import SwiftUI

final class SumsubPresenter: ObservableObject {
    private let verification = SumsubVerification()

    /// Call on the trigger (e.g. button tap). The SDK presents itself over the key
    /// window's root view controller and tears itself down on finish/close.
    func launch() {
        verification.start()
    }
}
