//
//  SumsubTheme.kt
//  Sumsub Mobile SDK theme for Android — generated by the sumsub-theme-msdk skill.
//
//  A factory, not a singleton: resources must resolve against a real Context, and
//  rebuilding per launch keeps the theme in sync with runtime day/night switches.
//  Attach on the SDK builder, before build():
//
//      SNSMobileSDK.Builder(activity)
//          .withTheme(sumsubTheme(activity))
//          ...
//
//  R.color.* / R.font.* names below are EXAMPLES — replace them with the host app's
//  actual resources (that's the point: the theme tracks the app's own tokens).
//  Import paths match the current SDK package layout (com.sumsub.sns.core.theme.*) —
//  let the IDE confirm/adjust them if your version differs. Theme API needs MSDK >= 1.26.
//

package com.example.app.sumsub

import android.content.Context
import android.content.res.Configuration
import android.graphics.Color
import android.graphics.Typeface
import androidx.annotation.ColorRes
import androidx.annotation.FontRes
import androidx.core.content.ContextCompat
import androidx.core.content.res.ResourcesCompat
import androidx.core.graphics.ColorUtils
import com.sumsub.sns.core.theme.SNSTheme
import com.sumsub.sns.core.theme.SNSThemeColor
import com.sumsub.sns.core.theme.SNSThemeFont
import com.sumsub.sns.core.theme.colors
import com.sumsub.sns.core.theme.fonts
import com.sumsub.sns.core.theme.metrics
import kotlin.math.roundToInt

/**
 * The six palette seeds, resolved for ONE appearance. Resolved twice below (light +
 * dark configuration contexts) so every color carries both variants explicitly —
 * an Android resource read returns only the current mode's value.
 *
 * Single-appearance app? Resolve once and use the one-argument SNSThemeColor(...).
 */
private class Seeds(ctx: Context) {
    val background = ctx.color(R.color.app_background)   // primary screen bg (not a card/surface color)
    val primary = ctx.color(R.color.brand_primary)       // accent — drives buttons, links, info
    val neutral = ctx.color(R.color.text_primary)        // dominant text color
    val success = ctx.color(R.color.state_success)
    val warning = ctx.color(R.color.state_warning)
    val critical = ctx.color(R.color.state_error)
}

fun sumsubTheme(context: Context): SNSTheme {
    val light = Seeds(context.inMode(night = false))
    val dark = Seeds(context.inMode(night = true))

    // Both appearances of one seed → SNSThemeColor(light, dark), optionally faded.
    fun seed(alpha: Float = 1f, pick: (Seeds) -> Int) =
        SNSThemeColor(pick(light).alpha(alpha), pick(dark).alpha(alpha))

    val white = SNSThemeColor(Color.WHITE)
    val transparent = SNSThemeColor(Color.TRANSPARENT)
    val cameraBg = 0xFF1A1A1A.toInt()                    // SDK's near-black default; keep unless the app overrides it

    return SNSTheme {
        colors {
            // Common
            navigationBarItem = seed(0.60f) { it.neutral }
            alertTint = seed { it.primary }
            statusBarColor = seed { it.background }       // status bar behind SDK screens — match backgroundCommon

            // Backgrounds — semantic surfaces derive from the strong seed, faded
            backgroundCommon = seed { it.background }
            backgroundNeutral = seed(0.05f) { it.neutral }
            backgroundInfo = seed(0.10f) { it.primary }   // info IS the accent — no separate seed
            backgroundSuccess = seed(0.20f) { it.success }
            backgroundWarning = seed(0.10f) { it.warning }
            backgroundCritical = seed(0.20f) { it.critical }

            // Content
            contentLink = seed { it.primary }
            contentStrong = seed { it.neutral }
            contentNeutral = seed(0.80f) { it.neutral }
            contentWeak = seed(0.80f) { it.neutral }
            contentInfo = seed { it.primary }
            contentSuccess = seed { it.success }
            contentWarning = seed { it.warning }
            contentCritical = seed { it.critical }

            // Primary button — label must hold >= 4.5:1 against the fill (Stage 2 check)
            primaryButtonBackground = seed { it.primary }
            primaryButtonBackgroundHighlighted = seed(0.80f) { it.primary }
            primaryButtonBackgroundDisabled = seed(0.40f) { it.primary }
            primaryButtonContent = white
            primaryButtonContentHighlighted = SNSThemeColor(Color.WHITE.alpha(0.80f))
            primaryButtonContentDisabled = SNSThemeColor(Color.WHITE.alpha(0.60f))

            // Secondary button (transparent style; filled apps set an explicit bg)
            secondaryButtonBackground = transparent
            secondaryButtonBackgroundHighlighted = seed(0.05f) { it.primary }
            secondaryButtonBackgroundDisabled = transparent
            secondaryButtonContent = seed { it.primary }
            secondaryButtonContentHighlighted = seed(0.80f) { it.primary }
            secondaryButtonContentDisabled = seed(0.50f) { it.primary }

            // Link button
            linkButtonContent = seed { it.primary }
            linkButtonContentDisabled = seed(0.50f) { it.primary }
            linkButtonBackgroundHighlighted = seed(0.05f) { it.primary }

            // Cards: cardPlainBackground / cardBorderedBackground stay at the SDK
            // default (transparent) — set them only if a *CardStyle metric is
            // switched to PLAIN / BORDERED (they'd show whatever is behind them).

            // Camera
            cameraBackground = SNSThemeColor(cameraBg)
            cameraBackgroundOverlay = SNSThemeColor(cameraBg.alpha(0.75f))
            cameraContent = white

            // Fields
            fieldBackground = seed(0.05f) { it.neutral }
            fieldBackgroundInvalid = seed(0.10f) { it.critical }
            fieldBorder = transparent             // visible-border apps: app border color + fieldBorderWidth = 1dp
            fieldBorderDisabled = transparent
            fieldBorderFocused = transparent      // focus-ring apps (Material outlined fields): seed { it.primary }
            fieldPlaceholder = seed(0.40f) { it.neutral }
            fieldContent = seed(0.80f) { it.neutral }
            fieldTint = seed { it.primary }

            // Lists, bottom sheet, progress
            listSeparator = seed(0.20f) { it.neutral }
            listSelectedItemBackground = seed(0.05f) { it.neutral }
            bottomSheetHandle = seed(0.20f) { it.neutral }
            bottomSheetBackground = seed { it.background }
            progressBarTint = seed { it.primary }
            progressBarBackground = seed(0.20f) { it.primary }
        }

        fonts {
            // Sizes are sp. No `button` slot on Android — button typography is SDK-managed.
            headline1 = SNSThemeFont(context.font(R.font.inter_bold, Typeface.DEFAULT_BOLD), 24)
            headline2 = SNSThemeFont(context.font(R.font.inter_bold, Typeface.DEFAULT_BOLD), 20)
            subtitle1 = SNSThemeFont(context.font(R.font.inter_semibold, Typeface.DEFAULT_BOLD), 18)
            subtitle2 = SNSThemeFont(context.font(R.font.inter_regular, Typeface.DEFAULT), 16)
            body = SNSThemeFont(context.font(R.font.inter_regular, Typeface.DEFAULT), 14)
            caption = SNSThemeFont(context.font(R.font.inter_regular, Typeface.DEFAULT), 12)
        }

        metrics {
            // Float metrics are PIXELS — always convert dp at build time.
            screenHorizontalMargin = context.dp(16f)      // match the app's dominant side padding
            buttonHeight = context.dp(48f)
            buttonCornerRadius = context.dp(8f)
            buttonBorderWidth = context.dp(1f)
            fieldHeight = context.dp(48f)
            fieldCornerRadius = context.dp(8f)
            fieldBorderWidth = context.dp(0f)             // 1dp if fieldBorder is non-transparent
            cardCornerRadius = context.dp(8f)
            cardBorderWidth = context.dp(1f)
            // activityIndicatorStyle, viewport / bottom-sheet / list-separator metrics,
            // *CardStyle enums and header alignments: left at SDK defaults on purpose.
        }
    }
}

// ---- Helpers ----------------------------------------------------------------

/** A context resolving resources in the given UI mode, so light + dark variants can both be read. */
private fun Context.inMode(night: Boolean): Context {
    val config = Configuration(resources.configuration)
    config.uiMode = (config.uiMode and Configuration.UI_MODE_NIGHT_MASK.inv()) or
            (if (night) Configuration.UI_MODE_NIGHT_YES else Configuration.UI_MODE_NIGHT_NO)
    return createConfigurationContext(config)
}

private fun Context.color(@ColorRes id: Int): Int = ContextCompat.getColor(this, id)

/** The Stage 2 alpha-derivation: fade a color to the given opacity fraction. */
private fun Int.alpha(fraction: Float): Int =
    if (fraction >= 1f) this else ColorUtils.setAlphaComponent(this, (fraction * 255).roundToInt())

private fun Context.dp(value: Float): Float = value * resources.displayMetrics.density

/** Font resource with a mandatory system fallback — a missing font must degrade, not crash. */
private fun Context.font(@FontRes id: Int, fallback: Typeface): Typeface =
    ResourcesCompat.getFont(this, id) ?: fallback
