//
//  SumsubTheme.swift
//  Generated by the sumsub-theme-msdk skill.
//
//  Maps the host app's design tokens onto the Sumsub Mobile SDK theme.
//  Full palette coverage: every SDK color/font/metric property is set.
//
//  ILLUSTRATIVE EXAMPLE — the skill replaces asset names, hex values,
//  font names, and numeric metrics with the tokens it finds in your project.
//
//  Usage — at the launch site, right after the SDK is created and before it is shown.
//  The theme is a plain property; how the SDK is presented does not matter:
//      sdk.theme = SumsubTheme()
//  For a @MainActor source under Swift 6 (or a runtime-switchable host theme), build it
//  via a factory instead: sdk.theme = SumsubTheme.make()   (see SKILL.md, Stage 3)
//

import UIKit
import IdensicMobileSDK

final class SumsubTheme: SNSTheme {

    override init() {
        super.init()

        // MARK: - Seed colors
        //
        // Asset-catalog colors carry light/dark variants automatically.
        // UIColor(named:) preserves that dynamic behavior end-to-end.
        // Fallbacks are system colors so the theme never crashes on a bad name.

        let background = UIColor(named: "BackgroundPrimary") ?? .systemBackground
        let accent     = UIColor(named: "AccentColor")       ?? .systemBlue
        let neutral    = UIColor(named: "LabelPrimary")      ?? .label
        let success    = UIColor(named: "StatusSuccess")     ?? UIColor(red: 0.15, green: 0.72, blue: 0.58, alpha: 1)
        let warning    = UIColor(named: "StatusWarning")     ?? UIColor(red: 0.95, green: 0.67, blue: 0.05, alpha: 1)
        let critical   = UIColor(named: "StatusCritical")    ?? UIColor(red: 0.94, green: 0.33, blue: 0.33, alpha: 1)
        let info       = accent   // app reuses accent for info states; replace if a separate blue exists

        // MARK: - Colors

        // --- Common ---
        colors.navigationBarItem = neutral.withAlphaComponent(0.6)
        colors.alertTint         = accent

        // --- Backgrounds ---
        colors.backgroundCommon   = background
        colors.backgroundNeutral  = neutral.withAlphaComponent(0.05)
        colors.backgroundInfo     = info.withAlphaComponent(0.1)
        colors.backgroundSuccess  = success.withAlphaComponent(0.2)
        colors.backgroundWarning  = warning.withAlphaComponent(0.1)
        colors.backgroundCritical = critical.withAlphaComponent(0.2)

        // --- Content (text / foreground) ---
        colors.contentLink     = accent
        colors.contentStrong   = neutral
        colors.contentNeutral  = neutral.withAlphaComponent(0.8)
        colors.contentWeak     = neutral.withAlphaComponent(0.8)
        colors.contentInfo     = info
        colors.contentSuccess  = success
        colors.contentWarning  = warning
        colors.contentCritical = critical

        // --- Primary button (accent fill, white label) ---
        colors.primaryButtonBackground            = accent
        colors.primaryButtonBackgroundHighlighted = accent.withAlphaComponent(0.8)
        colors.primaryButtonBackgroundDisabled    = accent.withAlphaComponent(0.4)
        colors.primaryButtonContent               = .white
        colors.primaryButtonContentHighlighted    = UIColor.white.withAlphaComponent(0.8)
        colors.primaryButtonContentDisabled       = UIColor.white.withAlphaComponent(0.6)

        // --- Secondary button (outlined: transparent bg, accent content) ---
        colors.secondaryButtonBackground            = .clear
        colors.secondaryButtonBackgroundHighlighted = accent.withAlphaComponent(0.05)
        colors.secondaryButtonBackgroundDisabled    = .clear
        colors.secondaryButtonContent               = accent
        colors.secondaryButtonContentHighlighted    = accent.withAlphaComponent(0.8)
        colors.secondaryButtonContentDisabled       = accent.withAlphaComponent(0.5)

        // --- Field / link buttons ---
        colors.fieldButtonBackgroundHighlighted = neutral.withAlphaComponent(0.05)
        colors.linkButtonBackgroundHighlighted  = accent.withAlphaComponent(0.05)
        colors.linkButtonContent                = accent
        colors.linkButtonContentDisabled        = accent.withAlphaComponent(0.5)

        // --- Cards ---
        // nil = transparent; SDK renders card shape via metrics alone.
        colors.cardPlainBackground    = nil
        colors.cardBorderedBackground = nil

        // --- Camera (near-black background) ---
        colors.cameraBackground        = UIColor(white: 0.1, alpha: 1)
        colors.cameraBackgroundOverlay = UIColor(white: 0.1, alpha: 0.8)
        colors.cameraContent           = UIColor.white.withAlphaComponent(0.8)

        // --- Fields ---
        colors.fieldBackground        = neutral.withAlphaComponent(0.05)
        colors.fieldBackgroundInvalid = critical.withAlphaComponent(0.1)
        colors.fieldBorder            = .clear       // borderless; set fieldBorderWidth = 0 below
        colors.fieldPlaceholder       = neutral.withAlphaComponent(0.4)
        colors.fieldContent           = neutral.withAlphaComponent(0.8)
        colors.fieldTint              = accent

        // --- List ---
        colors.listSeparator              = neutral.withAlphaComponent(0.2)
        colors.listSelectedItemBackground = neutral.withAlphaComponent(0.05)

        // --- Bottom sheet ---
        colors.bottomSheetHandle     = neutral.withAlphaComponent(0.2)
        colors.bottomSheetBackground = background

        // --- Toolbar ---
        colors.toolbarTint       = accent
        colors.toolbarBackground = nil

        // --- Progress bar ---
        // progressBarShimmer needs separate light/dark values (shimmer over the progress track).
        colors.progressBarShimmer = UIColor { traits in
            traits.userInterfaceStyle == .dark
                ? UIColor.white.withAlphaComponent(0.2)
                : UIColor.white.withAlphaComponent(0.5)
        }
        colors.progressBarBackground = accent.withAlphaComponent(0.2)
        colors.progressBarTint       = accent

        // MARK: - Fonts
        //
        // UIFont(name:size:) returns nil if the font is not bundled and registered
        // in UIAppFonts. The ?? fallback ensures the SDK never gets a nil font.

        fonts.headline1 = UIFont(name: "Inter-Bold",     size: 24) ?? .systemFont(ofSize: 24, weight: .bold)
        fonts.headline2 = UIFont(name: "Inter-Bold",     size: 20) ?? .systemFont(ofSize: 20, weight: .bold)
        fonts.subtitle1 = UIFont(name: "Inter-SemiBold", size: 18) ?? .systemFont(ofSize: 18, weight: .semibold)
        fonts.subtitle2 = UIFont(name: "Inter-Regular",  size: 16) ?? .systemFont(ofSize: 16, weight: .regular)
        fonts.body      = UIFont(name: "Inter-Regular",  size: 14) ?? .systemFont(ofSize: 14, weight: .regular)
        fonts.button    = UIFont(name: "Inter-SemiBold", size: 18) ?? .systemFont(ofSize: 18, weight: .semibold)
        fonts.caption   = UIFont(name: "Inter-Regular",  size: 12) ?? .systemFont(ofSize: 12, weight: .regular)

        // MARK: - Metrics

        metrics.buttonHeight       = 52    // from app's primary button height
        metrics.buttonCornerRadius = 12    // app-wide rounded corners
        metrics.buttonBorderWidth  = 1     // secondary button border

        metrics.fieldHeight        = 52
        metrics.fieldCornerRadius  = 12
        metrics.fieldBorderWidth   = 0     // borderless fields (fieldBorder = .clear above)

        metrics.cardCornerRadius   = 12    // consistent with field/button
        metrics.cardBorderWidth    = 1

        metrics.screenHorizontalMargin = 20    // app's dominant screen side padding (drives all horizontal insets)

        // Status bar: derived from light-mode background luminance.
        // BackgroundPrimary ≈ #F5F5F5 → luminance ≈ 0.96 → .default (dark icons on light bg).
        metrics.commonStatusBarStyle = .default
        metrics.cameraStatusBarStyle = .default
    }
}
